### ISSUE TITLE
Smoothing

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#108]
# Brainstorm

## Ingredients

* given a node, identify if on interior, interface, or surface
  * if surface and interface, classify as interface
  * having those nodesets would help

## Plan

* Laplace everywhere - easiest first step - everything melts to a point
* Laplace on interior without moving surface/interface nodes (for dualized meshes already projected to the boundary)
* Taubin
* Reproduce the Chen

Combinatorial options for hierarchical smoothing (surface, interface, interior)
* surface only
  * surface plus interior influence zone (avoid creating bad quality elements near the surface)
* interface only
  * interface plus interior influence zone
* interior only
  * "leave the surface alone" (as it has already been projected, e.g., to the .stl surface), but smooth interior
  * Reference https://github.com/sandialabs/sibl/blob/master/geo/doc/dual/lesson_04c.md
* ignore entire blocks option
* hierarchical smoothing (surface to surface

Mesh -> Smooth Mesh options

* Mesh in progress, or
* Existing mesh then smooth

## See also

* https://autotwin.github.io/automesh/theory/smoothing.html

**Comment by hovey** [comment]
@mrbuche Some prototype Python code (https://autotwin.github.io/automesh/examples/smoothing/index.html) and some Laplace smoothing results, all FREE nodes, no hierarchical smoothing.

**Comment by mrbuche** [comment]
@hovey I will hopefully get started on this tomorrow. Having too much fun with speeding this up!

**Comment by mrbuche** [comment]
I think we have everything except Taubin, and some of the details for the specifications have sort of changed, so I am going to close this -- we know where we are going!
