### ISSUE TITLE
Feature: mesh progress

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#113]
## Given

A mesh generation step that takes a long process time, 

```sh
 (main) chovey@s1088757/Users/chovey/autotwin/automesh/book/examples/spheres_cont> 
automesh -i spheres_resolution_4.npy -o spheres_resolution_4.inp \
                                                                                       -x 240 -y 240 -z 240 \
                                                                                       --xtranslate -12 --ytranslate -12 --ztranslate -12
    automesh 0.1.7
     Reading spheres_resolution_4.npy
        Done 6.732708ms
     Meshing spheres_resolution_4.inp [xtranslate: -12, ytranslate: -12, ztranslate: -12]
```

## Idea for Consideration

@mrbuche what do you think about giving some type of mesh progress indication feedback on the command line?  The process above seems to take several hours.  Intermittent feedback on the command line might provide users with more confidence that the calculation is proceeding normally.  What are your thoughts?

**Comment by hovey** [comment]
@mrbuche the 4th case never finished, despite day-long waits and several attempts.

**Comment by mrbuche** [comment]
sad :( maybe we should also separate the meshing progress from file writing progress, in order to compare those timings too.

**Comment by hovey** [comment]
That sound like a great idea! 💡

**Comment by mrbuche** [comment]
@hovey good news, it's actually just the node renumbering that is killing our performance. So filtering out the air is not a big deal after all. We might even be faster than Sculpt without the renumbering. Maybe we can make it more efficient, otherwise we should consider making it optional.

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">--</font> <font color="#00AFFF">mesh</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">spheres_resolution_2.npy</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">target/foo.inp</u></font>
<font color="#EC00FF"><b>    automesh 0.1.7</b></font>
     <font color="#58C7E2"><b>Reading</b></font> spheres_resolution_2.npy
        <font color="#54E484"><b>Done</b></font> 231.754µs
     <font color="#58C7E2"><b>Meshing</b></font> target/foo.inp
      <font color="#E0B401"><b>Filter</b></font> 2.552869ms
<font color="#E0B401"><b>Connectivity</b></font> 1.775562ms
 <font color="#E0B401"><b>Renumbering</b></font> 9.539023211s
 <font color="#E0B401"><b>Coordinates</b></font> 3.906466ms
        <font color="#54E484"><b>Done</b></font> 9.54765232s
     <font color="#58C7E2"><b>Writing</b></font> target/foo.inp
        <font color="#54E484"><b>Done</b></font> 79.338268ms
</pre>

**Comment by hovey** [comment]
Hey @mrbuche that analysis is really helpful.  Filtering out air but retaining gaps in node numbering might not be too bad of a solution.  I don't know if Abaqus requires sequential node numbers or not.  

I **really** appreciate the deep dive to uncover the bottleneck.  Making node renumber more efficient would be my first choice,  though I don't know to what degree that is possible yet.  

Making the node renumbering optional sounds like a good compromise.  It would allow smaller problems to have renumbered nodes, but the larger problems would remain intractable (unless we can figure out a better renumber algorithm).  

Hope to this discuss this tomorrow.   Thanks again!

**Comment by mrbuche** [comment]
Yeah we need to dig into this further. Sculpt doesn't need the renumbering because it includes the air, so it can also be fast. And I think we need to use the old algorithm for nodal coordinates if we don't renumber. And hopefully it's Ok with Abaqus and Exodus not to renumber if we can't.

**Comment by mrbuche** [comment]
@hovey here it is with the new changes in #125. We are much faster now, and appear to be limited by writing speed.

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">--</font> <font color="#00AFFF">mesh</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">spheres_resolution_4.npy</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">target/foo.inp</u></font>
<font color="#EC00FF"><b>    automesh 0.1.7</b></font>
     <font color="#58C7E2"><b>Reading</b></font> spheres_resolution_4.npy
        <font color="#54E484"><b>Done</b></font> 5.557846ms
     <font color="#58C7E2"><b>Meshing</b></font> target/foo.inp
        <font color="#54E484"><b>Done</b></font> 1.459777859s
     <font color="#58C7E2"><b>Writing</b></font> target/foo.inp
        <font color="#54E484"><b>Done</b></font> 9.66507243s</pre>

We also have a new `profile` feature to show more details in the CLI output:

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">-F</font> <font color="#00AFFF">profile</font> <font color="#00AFFF">--</font> <font color="#00AFFF">mesh</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">spheres_resolution_4.npy</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">target/foo.inp</u></font>
<font color="#EC00FF"><b>    automesh 0.1.7</b></font>
     <font color="#58C7E2"><b>Reading</b></font> spheres_resolution_4.npy
        <font color="#54E484"><b>Done</b></font> 6.190101ms
     <font color="#58C7E2"><b>Meshing</b></font> target/foo.inp
           <font color="#E0B401"><b>⤷ Filter</b></font> 361.277566ms
             <font color="#E0B401"><b>Connectivity</b></font> 308.521504ms
             <font color="#E0B401"><b>Coordinates</b></font> 680.769942ms
             <font color="#E0B401"><b>Mapping</b></font> 38.775263ms
             <font color="#E0B401"><b>Removal</b></font> 11.470454ms
             <font color="#E0B401"><b>Renumbering</b></font> 32.854185ms
        <font color="#54E484"><b>Done</b></font> 1.457778705s
     <font color="#58C7E2"><b>Writing</b></font> target/foo.inp
        <font color="#54E484"><b>Done</b></font> 8.91187227s</pre>

**Comment by mrbuche** [comment]
more for writing operation

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">-F</font> <font color="#00AFFF">profile</font> <font color="#00AFFF">--</font> <font color="#00AFFF">mesh</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">spheres_resolution_4.npy</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">target/foo.inp</u></font>
<font color="#EC00FF"><b>    automesh 0.1.7</b></font>
     <font color="#58C7E2"><b>Reading</b></font> spheres_resolution_4.npy
        <font color="#54E484"><b>Done</b></font> 6.571816ms
     <font color="#58C7E2"><b>Meshing</b></font> target/foo.inp
           <font color="#E0B401"><b>⤷ Filter</b></font> 328.190311ms
             <font color="#E0B401"><b>Connectivity</b></font> 288.739794ms
             <font color="#E0B401"><b>Coordinates</b></font> 693.354529ms
             <font color="#E0B401"><b>Mapping</b></font> 40.535795ms
             <font color="#E0B401"><b>Removal</b></font> 12.382891ms
             <font color="#E0B401"><b>Renumbering</b></font> 34.838694ms
        <font color="#54E484"><b>Done</b></font> 1.419328441s
     <font color="#58C7E2"><b>Writing</b></font> target/foo.inp
           <font color="#E0B401"><b>⤷ Coordinates</b></font> 4.651333564s
             <font color="#E0B401"><b>Connectivity</b></font> 4.090584214s
        <font color="#54E484"><b>Done</b></font> 9.350897612s
</pre>

**Comment by mrbuche** [comment]
I'm gonna close this since meshing progress bar seems hard and we are blazingly fast now anyway...
