### ISSUE TITLE
Node-to-element connectivity is slow.

### ISSUE THREAD

**Issue by mrbuche** [autotwin/automesh#133]
**Describe the bug**

The calculation of the node-to-element connectivity appears to be much slower than other operations.

**To Reproduce**

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">-F</font> <font color="#00AFFF">profile</font> <font color="#00AFFF">--</font> <font color="#00AFFF">mesh</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">spheres_resolution_2.npy</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">target/foo.inp</u></font>
<font color="#EC00FF"><b>    automesh 0.1.10</b></font>
     <font color="#58C7E2"><b>Reading</b></font> spheres_resolution_2.npy
        <font color="#54E484"><b>Done</b></font> 201.338µs
     <font color="#58C7E2"><b>Meshing</b></font> target/foo.inp
           <font color="#E0B401"><b>⤷ Filter</b></font> 3.053172ms
             <font color="#E0B401"><b>Connectivity</b></font> 1.756722ms
             <font color="#E0B401"><b>Coordinates</b></font> 5.495238ms
             <font color="#E0B401"><b>Mapping</b></font> 492.783µs
             <font color="#E0B401"><b>Removal</b></font> 61.794µs
             <font color="#E0B401"><b>Renumbering</b></font> 193.295µs
        <font color="#54E484"><b>Done</b></font> 11.419183ms
   <font color="#58C7E2"><b>Smoothing</b></font> target/foo.inp
           <font color="#E0B401"><b>⤷ Node-to-element connectivity</b></font> 8.314554166s 
             <font color="#E0B401"><b>Node-to-node connectivity</b></font> 26.056589ms 
             <font color="#E0B401"><b>Nodal hierarchy</b></font> 7.161734ms 
        <font color="#54E484"><b>Done</b></font> 8.347809164s
     <font color="#58C7E2"><b>Writing</b></font> target/foo.inp
           <font color="#E0B401"><b>⤷ Coordinates</b></font> 34.842501ms
             <font color="#E0B401"><b>Connectivity</b></font> 24.634797ms
        <font color="#54E484"><b>Done</b></font> 66.325293ms</pre>

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">-F</font> <font color="#00AFFF">profile</font> <font color="#00AFFF">--</font> <font color="#00AFFF">mesh</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">spheres_resolution_3.npy</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">target/foo.inp</u></font>
<font color="#EC00FF"><b>    automesh 0.1.10</b></font>
     <font color="#58C7E2"><b>Reading</b></font> spheres_resolution_3.npy
        <font color="#54E484"><b>Done</b></font> 487.264µs
     <font color="#58C7E2"><b>Meshing</b></font> target/foo.inp
           <font color="#E0B401"><b>⤷ Filter</b></font> 22.320514ms
             <font color="#E0B401"><b>Connectivity</b></font> 18.962217ms
             <font color="#E0B401"><b>Coordinates</b></font> 46.409529ms
             <font color="#E0B401"><b>Mapping</b></font> 2.836481ms
             <font color="#E0B401"><b>Removal</b></font> 558.733µs
             <font color="#E0B401"><b>Renumbering</b></font> 2.519586ms
        <font color="#54E484"><b>Done</b></font> 95.556747ms
   <font color="#58C7E2"><b>Smoothing</b></font> target/foo.inp
           <font color="#E0B401"><b>⤷ Node-to-element connectivity</b></font> 768.169208482s 
             <font color="#E0B401"><b>Node-to-node connectivity</b></font> 233.107442ms 
             <font color="#E0B401"><b>Nodal hierarchy</b></font> 57.136488ms 
        <font color="#54E484"><b>Done</b></font> 768.459505013s
     <font color="#58C7E2"><b>Writing</b></font> target/foo.inp
           <font color="#E0B401"><b>⤷ Coordinates</b></font> 261.19101ms
             <font color="#E0B401"><b>Connectivity</b></font> 224.191682ms
        <font color="#54E484"><b>Done</b></font> 551.462813ms
</pre>

**Expected behavior**

Appears to be $O(N^2)$ rather than $O(N)$, which is likely due to looping over the element-to-node connectivity within the loop over the node-to-element connectivity in order to populate it.

**Additional context**

Reproduce using [this commit](https://github.com/autotwin/automesh/commit/f1fd1ddb2e7220fcd7dbacfad7977f841ab41692). The node-to-element connectivity is currently needed to calculate the node-to-node connectivity and the nodal hierarchy.

**Comment by mrbuche** [comment]
$ cargo run -qr -F profile -- mesh -i spheres_resolution_4.npy -o target/foo.inp
    automesh 0.1.10
     Reading spheres_resolution_4.npy
        Done 5.722221ms
     Meshing target/foo.inp
           ⤷ Filter 350.079132ms
             Connectivity 309.399188ms
             Coordinates 698.335739ms
             Mapping 39.217639ms
             Removal 12.48971ms
             Renumbering 38.316884ms
        Done 1.467550975s
   Smoothing target/foo.inp
           ⤷ Node-to-element connectivity 483.130824ms 
             Node-to-node connectivity 5.295012793s 
             Nodal hierarchy 846.817194ms 
        Done 6.625028545s
     Writing target/foo.inp
           ⤷ Coordinates 4.520938614s
             Connectivity 3.909102393s
        Done 9.050382541s

**Comment by hovey** [comment]
@mrbuche 
Just finished new timing results with `automesh` version `0.0.10`
