### ISSUE TITLE
Taubin smoothing

### ISSUE THREAD

**Issue by mrbuche** [autotwin/automesh#169]
There are some requirements on the Taubin smoothing parameters in order for it to become a low-pass filter.

`automesh` should automatically determine as many parameters as possible from the mesh and limit user input.

**Comment by hovey** [comment]
Yes, I agree, let me work on this item.

**Comment by hovey** [comment]
@mrbuche I updated the smoothing theory part of the mdbooks (and am doing the code check in now).  

It appears from Taubin's manuscript (https://dl.acm.org/doi/pdf/10.1145/218380.218473) that setting the values should be implemented:

```sh
# defaults
k_PB = 0.1
lambda = 0.6307
mu = lambda / (k_PB * lambda - 1.0)

# constraints to user-override of the defaults
0.0 < k_PB < 1.0
0.0 < lambda < 1.0
mu = lambda / (k_PB * lambda - 1.0)
```

**Comment by mrbuche** [comment]
@hovey seems like it's the best idea to let the user specify lambda and the kBP, the band-pass frequency, and the number of iterations.

I'm finding that changing the band-pass frequency away from the default 0.1 (say, to 0.01) can be pretty consequential. Maybe we can find some way to calculate a good default band pass frequency based on the mesh, lambda, and the number of iterations?

**Comment by hovey** [comment]
Regarding,

> I'm finding that changing the band-pass frequency away from the default 0.1 (say, to 0.01) can be pretty consequential, getting rid of these weird ripple effects and stuff. Maybe we can find some way to calculate a good default band pass frequency based on the mesh, lambda, and the number of iterations?

That's a great question, and the answer I think I have some ideas to discuss on Wednesday.  The hierarchical smoothing, too, I will hope to discuss in voice on Wednesday.  

We want smoothing for better fidelity to the underlying geometry, and for better convergence.  But, smooth too much, and the element min scaled Jacobians go from perfect to terrible, ruining any hope of a reasonable time step.  So, is there a Goldilocks solution?  Hmm... I don't know right now.

**Comment by mrbuche** [comment]
@hovey I just considered 1 iteration asked of the code to mean 1 of both, so with respect to the book, the user would be specifying 2k for the code.

**Comment by hovey** [comment]
> @hovey I just considered 1 iteration asked of the code to mean 1 of both, so with respect to the book, the user would be specifying 2k for the code.

Thanks for that clarification, I will update the mdbooks to reflect this implementation detail.
