### ISSUE TITLE
Quality Metrics

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#185]
<img width="765" alt="Screenshot 2024-11-06 at 10 34 01" src="https://github.com/user-attachments/assets/1943074d-f56d-4f75-ac2b-32f116eaf2f3">

<img width="762" alt="Screenshot 2024-11-06 at 10 34 15" src="https://github.com/user-attachments/assets/c5761a1b-441c-4a14-9139-7c53889118cb">

<img width="766" alt="Screenshot 2024-11-06 at 10 34 29" src="https://github.com/user-attachments/assets/ee23a7c0-cea1-479e-abed-76cccbdbb4ad">

<img width="764" alt="Screenshot 2024-11-06 at 10 36 37" src="https://github.com/user-attachments/assets/2ec093c2-09b2-4572-bb4d-f35a008ebbd7">

<img width="763" alt="Screenshot 2024-11-06 at 10 32 58" src="https://github.com/user-attachments/assets/9243b10a-27ea-435b-80a1-130a3ef102f3">

<img width="762" alt="Screenshot 2024-11-06 at 10 38 37" src="https://github.com/user-attachments/assets/8cb3bb31-0f78-4c6f-b4d0-f0441b981ab0">

**Comment by hovey** [comment]
SANDIA REPORT
SAND2007-1751
Unlimited Release
Printed March 2007
The Verdict Geometric Quality Library

https://www.osti.gov/servlets/purl/901967

**Comment by mrbuche** [comment]
MSJ in #192, can do other metrics in future.

**Comment by mrbuche** [comment]
#229
