### ISSUE TITLE
Python import of automesh module gives import error.

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#198]
**Describe the bug**
ImportError on Python CLI with loading automesh module

**To Reproduce**
```sh
(.venv)  (ost) chovey@machine/Users/chovey/recon3d> python
Python 3.11.9 (v3.11.9:de54cf5be3, Apr  2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import automesh as am
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chovey/recon3d/.venv/lib/python3.11/site-packages/automesh/__init__.py", line 1, in <module>
    from .automesh import *
ImportError: dlopen(/Users/chovey/recon3d/.venv/lib/python3.11/site-packages/automesh/automesh.cpython-311-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <D27B9254-7A13-3D51-AC56-FE702D6503B9> /Users/chovey/recon3d/.venv/lib/python3.11/site-packages/automesh/automesh.cpython-311-darwin.so
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file)
>>>
```

**Expected behavior**
The module loads and then I can use the module in Python.

**Screenshots**
n/a - python command line dump above

**Desktop (please complete the following information):**
 - OS: macOS 14.7
 - Version: automesh 0.2.2, python 3.11.9

**Comment by hovey** [comment]
Python package automesh is trying to load a shared library (`liblzma.5.dylib`) that it cannot find. This library is part of the xz compression library, which is often used for data compression.

https://crates.io/crates/xz

**Comment by mrbuche** [comment]
that is weird, I dont get the same errors on Ubuntu, and the Mac runners dont seem to have any issues

**Comment by hovey** [comment]
yeah, maybe my mac is deficient some how, I will tinker with it more...  stay tuned 🤓

**Comment by hovey** [comment]
To find `liblzma.5.dylib`

```sh
sudo find / -name "liblzma.5.dylib" 2>/dev/null
```

**Comment by hovey** [comment]
@mrbuche 
This seems like a really nasty one to debug.  Basically, I think there is something with how `automesh` is compiled, that it wants to seek out `liblzam` only in `homebrew` locations where I don't have it installed...

```sh
automesh.cpython-311-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <D27B9254-7A13-3D51-AC56-FE702D6503B9> /Users/chovey/recon3d/.venv/lib/python3.11/site-packages/automesh/automesh.cpython-311-darwin.so
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file)
```

Do you know if the macOS runners use homebrew?

**Comment by mrbuche** [comment]
I do not think the runner use homebrew, this is definitely a strange one. Dependencies of dependencies are fun! From `cargo tree` it looks like it might be xz2, a dependency of dependency vtkio. Does the CLI work fine? I would think there would be an issue there as well since the Python build would not compile those parts differently, but maybe not.

**Comment by mrbuche** [comment]
#203
