### ISSUE TITLE
For discussion: how to have all segmentation integers included

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#199]
For `letter_f_3d.npy` (https://autotwin.github.io/automesh/examples/unit_tests/index.html#letter-f-in-3d) I can use 

```sh
automesh mesh -i letter_f_3d.npy -o letter_f_3d_two_material.exo -r 2
```

to get both segmentation item `0` and `1` to appear in the mesh (there is no segmentation with ID `2` in this example), viz.,

<img width="663" alt="Screenshot 2024-11-11 at 20 51 23" src="https://github.com/user-attachments/assets/cadd259b-174f-4438-8fde-68ccaa7d7400">

But, this (the `-r 2` construct) seems like a fairly unnatural way to accomplish this outcome.   

## Question

Would changing the API from

```sh
Usage: automesh mesh [OPTIONS] --input <FILE> --output <FILE> [COMMAND]

Commands:
  smooth  Applies smoothing to the mesh before output
  help    Print this message or the help of the given subcommand(s)

Options:
...
  -r, --remove <ID>       Voxel IDs to remove from the mesh [default: 0]
...
``` 

to

...
```sh
Usage: automesh mesh [OPTIONS] --input <FILE> --output <FILE> [COMMAND]

Commands:
  smooth  Applies smoothing to the mesh before output
  help    Print this message or the help of the given subcommand(s)

Options:
...
  -r, --remove <ID>       Voxel IDs to remove from the mesh
...
```

be better?

**Comment by mrbuche** [comment]
@hovey definitely makes more sense to me, I guess it is a bit awkward to have to override the default in a roundabout way, I can make that change

**Comment by hovey** [comment]
Much appreciated 👍

**Comment by mrbuche** [comment]
#200
