### ISSUE TITLE
Quadtree balancing

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#208]
https://youtu.be/Ac47eHdSZuE

See also slides
https://i11www.iti.kit.edu/_media/teaching/winter2015/compgeom/algogeom-ws15-vl11-printable.pdf

**Comment by hovey** [comment]
For a quadtree with two points, the maximum level $\ell$ of the quadtree is known.  (See proof: https://youtu.be/Ac47eHdSZuE?si=rM5Zie3K_07I4hmO&t=750)

* let $c$ be the distance between those two points, 
* let $s$ be the side length distance of the root cell, level $\ell = 0$,

$\ell = \log(s/c) + \frac{1}{2}$

**Comment by hovey** [comment]
Finding neighbors:

https://youtu.be/Ac47eHdSZuE?si=UFh8oFtydPextoxy&t=854

**Comment by hovey** [comment]
Balanced quad trees:

https://youtu.be/Ac47eHdSZuE?si=xmp4TFIS1LpqnQ_7&t=1027

**Comment by hovey** [comment]
Neighbor finding:
https://faculty.sites.iastate.edu/jia/files/inline-files/29.%20quadtrees.pdf
page 76/111

**Comment by hovey** [comment]
Balancing algorithm, 
https://faculty.sites.iastate.edu/jia/files/inline-files/29.%20quadtrees.pdf
page 95/111

**Comment by mrbuche** [comment]
maybe consider some of smallest cell stuff, might want to specify cells contain at most 1 point, instead of levels

**Comment by hovey** [comment]
Hmm.. I hope we can discuss this...
