### ISSUE TITLE
Note on quadtree convention

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#209]
Hey @mrbuche 
I may have mislead you earlier... I was reviewing some literature, and found that there is convention that if a seed lies on the boundary of a cell, it is considered "inside" the cell if the seed lies on the bottom edge or left edge, and "outside" the cell if the cell lies on the top edge or right edge... so this line below and the line twice below it may need updates from `<=` to `<`,

https://github.com/autotwin/automesh/blob/c2b0d5f4895265322f8a2b16562cd821d0cd030f/tests/foo.rs#L23

https://github.com/autotwin/automesh/blob/c2b0d5f4895265322f8a2b16562cd821d0cd030f/tests/foo.rs#L25

But then again, maybe we find, on our journey toward balancing the tree, that we want to use `<=` instead of the traditional convention because we will wind up balancing it anyway... dunno, just wanted to communicate the convention for now.  :-)

**Comment by hovey** [comment]
One more note on indexing, binary space partitioning quadtree for a 2D index, https://en.wikipedia.org/wiki/Quadtree, 

<img width="562" alt="Screenshot 2024-11-15 at 22 32 03" src="https://github.com/user-attachments/assets/d8971a00-7e6a-4630-8d7c-0968d5c26d98">

**Comment by mrbuche** [comment]
for octree-ing a segmentation, we need even more options (do not subdivide whenever on any boundary)

**Comment by mrbuche** [comment]
Octrees not always symmetry (so meshes won't be) but hopefully internal smoothing will alleviate that.

![image](https://github.com/user-attachments/assets/f949dcfd-16da-42df-ab78-4b3287ad352e)

**Comment by mrbuche** [comment]
Extra padding has block num 0. Added option to remove any materials, like for meshing.

![image](https://github.com/user-attachments/assets/67cca576-1622-49cf-a847-aa269ab11f69)

**Comment by mrbuche** [comment]
Looking pretty nice for mesh adaptivity

![image](https://github.com/user-attachments/assets/a0b9c7c8-bbe9-4124-9b9c-aeec1859653e)

![image](https://github.com/user-attachments/assets/f7558d95-ab1f-4d9f-8bc9-5e93108fdc5d)
