### ISSUE TITLE
Possible `.spn` writer bug

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#232]
**Describe the bug**
The `.spn` output seems like it may have had a regression.

**To Reproduce**

On branch `cases`, section 6.1.2 (automesh/book/build/analysis/sphere_with_shells/timing_sculpt.html) Timing - Sculpt

**Expected behavior**
Expect the mesh to appear as is shown in section 6.1.1 (the `automesh` output `.exo`)

**Screenshots**

<img width="499" alt="Screenshot 2024-12-10 at 13 42 41" src="https://github.com/user-attachments/assets/4cd6bef4-f20f-49de-85ae-1e7bf6ebfa74">
<img width="476" alt="Screenshot 2024-12-10 at 13 42 21" src="https://github.com/user-attachments/assets/d63d78b1-93ee-4c7a-b545-c95ac21cdb12">
<img width="420" alt="Screenshot 2024-12-10 at 13 42 06" src="https://github.com/user-attachments/assets/95b80e19-30b6-4991-a39f-e961cd06bcf6">

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by mrbuche** [comment]
@hovey I can't reproduce this, can you show the exact steps from scratch starting from the file:
`book/examples/spheres_cont/spheres_resolution_1.npy`

Also make sure you reinstall `automesh` just in case.

**Comment by hovey** [comment]
@mrbuche I meant to assign this to me but not you (sorry if it went to you already)... I am trying to investigate and reproduce now.

**Comment by mrbuche** [comment]
seems to be a Sculpt problem
