### ISSUE TITLE
Discuss planes and simulation

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#245]
@mrbuche to for discussion on 2024-12-18:

On the `cases` branch, the `sr2` model.

`t=0` seconds:
<img width="715" alt="Screenshot 2024-12-17 at 14 31 29" src="https://github.com/user-attachments/assets/16197240-d239-4e0b-94ac-7b787864347a" />

`t=0.020` seconds:
<img width="721" alt="Screenshot 2024-12-17 at 14 32 05" src="https://github.com/user-attachments/assets/d11d173a-c2a7-4574-978a-69617d846c2f" />

**Comment by mrbuche** [comment]
I think that is a Paraview visualization issue
