### ISSUE TITLE
Sculpt timing

### ISSUE THREAD

**Issue by mrbuche** [autotwin/automesh#258]
We should probably use `--stair 3` when doing the `sculpt` [timings](https://github.com/autotwin/automesh/blob/main/book/analysis/sphere_with_shells/timing_sculpt.md), since that is allegedly the bare-bones voxel-to-mesh option. It seems to skip all the extra stuff that wouldn't be necessary, so it would be more fair.

Don't worry, `automesh` is still much faster (about 32 times faster in a 100x100x100 I just tried).

**Comment by hovey** [comment]
I will look into that and then update mdbooks.  Thanks.  On Dec 20, 2024, at 15:02, Michael R. Buche ***@***.***> wrote:﻿
Assigned #258 to @hovey.

**Comment by hovey** [comment]
@mrbuche 
Done.  Updated timings in #255 
See https://autotwin.github.io/automesh/analysis/sphere_with_shells/timing_sculpt.html
Also, I added relative time requirement table.

**Comment by mrbuche** [comment]
@hovey very cool thank you! now we can say automesh can be over 100x faster on a pretty fair comparison. also looks like it might get increasingly faster as the segmentation size goes up
