### ISSUE TITLE
For discussion: Clarification if scale and translate both specified

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#32]
If `scale` and `translate` are both specified as `non-unity` and `non-zero`, respectively, we want to clarify for the user through documentation and test, that the `scale` operation occurs first, the `translate` operation occurs second.  Otherwise, we may run into ambiguity if we translate, then scale (e.g., does the `scale` also move the translated origin?).

Example:

The origin from the `.npy` file is `(0., 0., 0.)`.  If we translate by an amount `(tx, ty, tz)`, the new origin becomes `(tx, ty, tz)`.  Then if we do isotropic scaling an amount `s`, ambiguity arises because we could make the second new origin `(s*tx, s*ty, s*tz)`, or we could simply leave the second new origin at `(tx, ty, tz)` and still scale the newly translated domain.

If we scale first and then translate second, we retain the origin at `(0., 0., 0.)` for the scaling, and then translation has only one interpretation.

I don't think Sculpt documented this order of operation clearly, or at least, it cause sufficient ambiguity in my mind previously that it generated a bug in a problem where I wanted to translate and scale in the same operation.

Thoughts?

**Comment by mrbuche** [comment]
Good point @hovey , I added a few things in #33 to address this.

- Short note in API docs, less important because users won't see it. CLI more important.
- Added notes to help for CLI, we could add more stuff there in the future. Looks like this:

```
$ automesh
Automatic mesh generation.

Notes:
  - Input/output file types are inferred.
  - Scaling is applied before translation.

Usage: automesh [OPTIONS] --input <INPUT> --output <OUTPUT>

Options:
  -i, --input <INPUT>            Name of the input file
  -o, --output <OUTPUT>          Name of the output file
  -x, --nelx <NELX>              Number of voxels in the x-direction [default: 0]
  -y, --nely <NELY>              Number of voxels in the y-direction [default: 0]
  -z, --nelz <NELZ>              Number of voxels in the z-direction [default: 0]
      --xscale <XSCALE>          Scale of coordinates in the x-direction [default: 1]
      --yscale <YSCALE>          Scale of coordinates in the y-direction [default: 1]
      --zscale <ZSCALE>          Scale of coordinates in the z-direction [default: 1]
      --xtranslate <XTRANSLATE>  Translation of coordinates in the x-direction [default: 0]
      --ytranslate <YTRANSLATE>  Translation of coordinates in the y-direction [default: 0]
      --ztranslate <ZTRANSLATE>  Translation of coordinates in the z-direction [default: 0]
  -h, --help                     Print help
  -V, --version                  Print version
```

**Comment by hovey** [comment]
* @mrbuche this looks awesome 👍 
* agree with you comments 100%
* will close this issue
