### ISSUE TITLE
Does negative translation not work?

### ISSUE THREAD

**Issue by hovey** [autotwin/automesh#88]
**Describe the bug**

```sh
automesh -i spheres_resolution_1.npy -o spheres_resolution_1.inp -x 24 -y 24 -z 24 --xtranslate -12 --ytranslate -12 --ztranslate -12
```

seems not to allow negative value translations, as this error occurs

```sh
error: unexpected argument '-1' found
```

**To Reproduce**

Follow documentation (work in progress) on `scale` branch, document: 

[`https://github.com/autotwin/automesh/tree/scale/book/examples/spheres_cont`](https://github.com/autotwin/automesh/tree/scale/book/examples/spheres_cont)

**Expected behavior**

Translation of the sphere so that the center of the sphere is at the origin, `(0, 0, 0)`.

**Desktop**

 - OS: macOS Sonoma v14.6.1
 - shell: fish v3.6.1

**Comment by mrbuche** [comment]
clap provides an attribute to enable negative numbers, see 390be4117bb82f29f7501bf490fc0a967a79c70b
